# Generates .cursor/mcp.env from .env for the Cognite MCP server.
# Secrets stay local and gitignored — never commit .cursor/mcp.env.

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$sourceEnv = Join-Path $root '.env'
$targetEnv = Join-Path $root '.cursor\mcp.env'

if (-not (Test-Path $sourceEnv)) {
  Write-Error ".env not found at $sourceEnv"
}

function Read-DotEnv {
  param([string]$Path)
  $vars = @{}
  Get-Content -Path $Path | ForEach-Object {
    $line = $_.Trim()
    if ($line -eq '' -or $line.StartsWith('#')) { return }
    $eq = $line.IndexOf('=')
    if ($eq -lt 1) { return }
    $key = $line.Substring(0, $eq).Trim()
    $value = $line.Substring($eq + 1).Trim()
    if ($value.StartsWith('"') -and $value.EndsWith('"')) {
      $value = $value.Substring(1, $value.Length - 2)
    }
    $vars[$key] = $value
  }
  return $vars
}

$source = Read-DotEnv -Path $sourceEnv

function Get-Var {
  param([string[]]$Names)
  foreach ($name in $Names) {
    if ($source.ContainsKey($name) -and $source[$name]) {
      return $source[$name]
    }
  }
  return $null
}

$clientId = Get-Var @('CDF_CLIENT_ID', 'IDP_CLIENT_ID')
$clientSecret = Get-Var @('CDF_CLIENT_SECRET', 'IDP_CLIENT_SECRET')
$tenantId = Get-Var @('CDF_TENANT_ID', 'IDP_TENANT_ID')
$cluster = Get-Var @('CDF_CLUSTER')
$project = Get-Var @('CDF_PROJECT')
$tokenUrl = Get-Var @('CDF_TOKEN_URL', 'IDP_TOKEN_URL')

$missing = @()
if (-not $clientId) { $missing += 'IDP_CLIENT_ID or CDF_CLIENT_ID' }
if (-not $clientSecret) { $missing += 'IDP_CLIENT_SECRET or CDF_CLIENT_SECRET' }
if (-not $tenantId) { $missing += 'IDP_TENANT_ID or CDF_TENANT_ID' }
if (-not $cluster) { $missing += 'CDF_CLUSTER' }
if (-not $project) { $missing += 'CDF_PROJECT' }

if ($missing.Count -gt 0) {
  Write-Error ("Missing required .env variables: {0}" -f ($missing -join ', '))
}

$dataModels = Get-Var @('CDF_DATA_MODELS')
if (-not $dataModels) {
  $dataModels = '[{"space":"APMAppData","externalId":"APMAppData","version":"13"}]'
}

$instanceSpaces = Get-Var @('CDF_INSTANCE_SPACES')
if (-not $instanceSpaces) {
  $instanceSpaces = '["APMAppData"]'
}

$lines = @(
  '# Auto-generated by scripts/sync-mcp-env.ps1 — do not commit',
  "CDF_CLIENT_ID=$clientId",
  "CDF_CLIENT_SECRET=$clientSecret",
  "CDF_TENANT_ID=$tenantId",
  "CDF_CLUSTER=$cluster",
  "CDF_PROJECT=$project",
  "CDF_DATA_MODELS=$dataModels",
  "CDF_INSTANCE_SPACES=$instanceSpaces"
)

if ($tokenUrl) {
  $lines += "CDF_TOKEN_URL=$tokenUrl"
}

$cursorDir = Split-Path -Parent $targetEnv
if (-not (Test-Path $cursorDir)) {
  New-Item -ItemType Directory -Path $cursorDir | Out-Null
}

Set-Content -Path $targetEnv -Value $lines -Encoding UTF8
Write-Host "Wrote $targetEnv (project: $project, cluster: $cluster)"
